# Generated by Django 3.0.3 on 2020-05-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_project_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(height_field=330, upload_to='home/images', width_field=185),
        ),
    ]
